### ISSUE TITLE
ctrl+alt -- up, down, left, right in XFCE

### ISSUE THREAD

**Issue by meoso** [ssokolow/quicktile#102]
```
/usr/local/bin/quicktile --daemonize
WARNING: Failed to bind key. It may already be in use: <Ctrl><Alt>leftarrow
WARNING: Failed to bind key. It may already be in use: <Ctrl><Alt>uparrow
WARNING: Failed to bind key. It may already be in use: <Ctrl><Alt>downarrow
WARNING: Failed to bind key. It may already be in use: <Ctrl><Alt>rightarrow
```

Xubuntu (XFCE)
i cannot locate anything bound to those keys.
i prefer to daemonize this, but the workaround `quicktile top`, etc works

edit: but then i just found XFCE has this feature built into the windows manager (excludes dialog boxes).... guess i'm lost in space.  quicktile has been a go-to staple for me, thank you.

**Comment by ssokolow** [comment]
> edit: but then i just found XFCE has this feature built into the windows manager (excludes dialog boxes).... guess i'm lost in space. quicktile has been a go-to staple for me, thank you.

Can I close this, then or is there a feature request in this that I'm not seeing?
