### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [ssokolow/quicktile#105]
Hi. I'm considering making a Debian package for Quicktile. Made one for superswitcher last week ref https://github.com/fidergo-stephane-gourichon/superswitcher/ . Works perfectly for me, builds on several Debian and Ubuntu releases (tested in Docker containers).

>  last time I tried to learn to make DEB packages, the docs that Google turned up were horrendous (and the official Debian viewpoint seemed to be "Don't try to be your own package maintainer. You'll only screw it up."),

Things seem to have improved somehow. There's a mindset to catch I think. Still, 
I have so far no strong claim regarding any conformance. I have followed official Debian tutorials and got hints on IRC (OTFC/#packaging), so I might not be that off after all.

Of course, I'm also aware that creating a `debian` subdirectory that allows locally creating a `deb` file is only part of the path. Still, if done properly enough, it can be something the rest can be built upon. For example, if I provide foundations for a Debian package, it can help with issue #72.

Anyway, all feedback welcome. I'll do it for the benefit of my relatives and me anyway, so why not sharing.

**Comment by ssokolow** [comment]
I'm going to close this so all further discussion can take place on #106. (Which should tell you how serious I am when I say I plan to merge it after I better understand what it's doing.)
