### ISSUE TITLE
QuickTile needs a more polished GitHub Pages site

### ISSUE THREAD

**Issue by ssokolow** [ssokolow/quicktile#12]
The QuickTile site is functional, but not really very good as a means of impressing visitors. I should really give it a proper redesign with some of the following features:

* [x] Important details and links should be made more prominent so they don't risk getting lost among the rest of the text.
* [x] More distinctive, memorable, and professional-looking.
* [x] A logo that can also be put up on [Open Hub](https://www.openhub.net/p/quicktile/).
* [x] Mention the lack of a tray icon as a feature. (One which will be preserved as an option should I ever implement one)
* [x] Perhaps a bit of Javascript to check the browser's User-Agent string and, if the user is on OSX or Windows, amend the X11 requirement note to suggest a platform-appropriate alternative?
* [x] An animation in the style of a demonstration video (to complement the illustrations in the command reference)
* [x] Finish migrating the information from the current site to the new Sphinx-based design

**EDIT:** I've started to revise and check off the list according to the copy of the `gtk3_port` branch on my hard drive with the rewritten Sphinx documentation.

**Comment by ssokolow** [comment]
Done in the push I'm preparing for the `gtk3_port` branch. One of the commits there that will auto-close this when pushed.

**Comment by fidergo-stephane-gourichon** [comment]
Where is the result to be seen? https://quicktile.github.io/ replies 404.

**Comment by ssokolow** [comment]
http://ssokolow.com/quicktile/ as linked in the repository header and the README.

That's where it's been since before github bought `github.io`. (Prior to that, it was at `http://ssokolow.github.com/quicktile/`)
