### ISSUE TITLE
Control-C on `quicktile --daemonize` can hang X on LXDE

### ISSUE THREAD

**Issue by coventry** [ssokolow/quicktile#129]
The manual recommends Ctrl-C after testing the install, in the installation section. This crashed X on my Lubuntu Virtualbox VM, and caused strange behavior on my host ubuntu system (Ctrl-Tab only showed VM windows, plus a "windows" box which seemingly did nothing.) The host system was fine after I rebooted the VM, though.

**Comment by ssokolow** [comment]
Not a QuickTile bug. All QuickTile does is restore the default `SIGINT` handler, which causes QuickTile to exit.

If your X is crashing because it has a bug which causes it to crash under certain circumstances when a program unexpectedly goes away, then that's a bug in X.
