### ISSUE TITLE
No errors and no funcionality on Ubuntu 20.04

### ISSUE THREAD

**Issue by ddmendes** [ssokolow/quicktile#130]
Hi, I use Ubuntu 20.04 and just cloned and run `quicktile.sh --daemonize` but it takes no effect and don't drop any message on console as well.

Tried to set it to launch on startup but checking with `ps -ax | grep quicktile` I cannot find its process (so I believe it didn't start).

Just moved from Pop OS to Ubuntu and I'm missing tiling but also I don't want auto-tiling as Pop does. This tool would fit perfectly.

**Comment by ddmendes** [comment]
Sorry, using notebook without keypad. Got confused about the shortcuts. Once I figured out that KP_1 was keypad 1 and removed all the KP_ from the config then it worked.

**Comment by skwzrd** [comment]
KP = Keypad / Numpad, not the row of numbers at the top of the characters. Thank you!
