### ISSUE TITLE
Failed to load module "xapp-gtk3-module"

### ISSUE THREAD

**Issue by jrpenaneto** [ssokolow/quicktile#132]
When I run quicktile from terminal I get the message:

Gtk-Message: 15:11:45.930: Failed to load module "xapp-gtk3-module"

Any hints? Thanks.

**Comment by ssokolow** [comment]
It's nothing to do with QuickTile and should be harmless. It's basically GTK saying "you set an environment variable that asks me to load the XApp plugin in all applications, and I couldn't".

A quick google says this is what the XApp plugin does:

> - Initializes the favorites:// vfs and adds a Favorites shortcut
>   to any gtk3 sidebars (like in file dialogs).
> 
> - Overrides the window icon for any GtkWindows when an environment
>   variable is set with an icon path or name.

...neither of which is relevant to QuickTile since it doesn't use the VFS, doesn't use file dialogs, and doesn't draw any windows of its own.

**Comment by jrpenaneto** [comment]
Thank you.

Actually QuickTile works ok. However after power manager suspends system
KP_number keys stop working. KP_Enter and letters (V, H, C) keep working
ok.



Em qui., 11 de nov. de 2021 às 16:03, Stephan Sokolow <
***@***.***> escreveu:

**Comment by ssokolow** [comment]
That's outside QuickTile's scope. QuickTile asks X11 for an exclusive grab on keys until further notice, so if a suspend is breaking some keys but not others, then something's wrong with your input system in a way that's causing it to break its promises.

(Do you have a customized keyboard layout? I've seen lots of things which can unexpectedly reset those.)

**Comment by jrpenaneto** [comment]
Got it.

My keyboard is a standard Brazilian one chosen from distro install menu.

Em ter., 16 de nov. de 2021 às 16:28, Stephan Sokolow <
***@***.***> escreveu:

**Comment by ssokolow** [comment]
> My keyboard is a standard Brazilian one chosen from distro install menu.

Then any resetting should be accepted as a bug rather than "operating as designed" by the maintainers of whatever's responsible for the problem.
