### ISSUE TITLE
Move window to other workspace

### ISSUE THREAD

**Issue by madhur** [ssokolow/quicktile#134]
Need a key shortcut for this.

**Comment by madhur** [comment]
I meant "Send the window and stay on the current workspace" to workspace #

**Comment by ssokolow** [comment]
QuickTile's architecture doesn't currently allow for commands to take arguments like workspace numbers and QuickTile already has `workspace-send-...` commands for the variants that I consider viable with the current architecture, as you can see in the [Command Reference](http://ssokolow.com/quicktile/commands.html).

Just edit your `quicktile.cfg` to map some keys to them.

**Comment by madhur** [comment]
Got it. Thanks
