### ISSUE TITLE
Feature: Be able to manually set shortcut combinations WITHOUT setting "ModMask" modifier key(s).

### ISSUE THREAD

**Issue by anandpathaksharma** [ssokolow/quicktile#42]
To start, finding this tool was super-awesome! I've just moved over from Windows to Xubuntu for my work environment (instead of Ubuntu because of several critical glitches with multi-monitor support and lagginess in Unity) and as such, despaired because moving to Xubuntu meant the loss of Compiz as the windows manager. 

To explain further, Compiz has _excellent_ advanced windows management tools that make binding key combinations to window positioning (via the **Put** extension). Finding Quicktile provided a replacement for the shortcuts that I use practically every fes seconds!

So, to the matter of this issue I'm creating. As the summary says, it is sometimes useful to be able to **not** use the "ModMask" value so that we can dictate _different_ modifier combinations for each of the available options.

My use case is that I've got `<Shift><Alt><F>` bound to a mouse key from when I was on windows (is a Logitech G700) that is not configurable on Ubuntu. Apart from the fact that the mouse's hardware keys can't be re-bound directly from Xubuntu, I have the same set of keys bound across many computers for these window management shortcuts.

What I would hope for is to be able to set the value of "ModMask" to something like "None" and if such a value is detected, the script should can set the "ModMask" to an empty string. This was the simplest way to modify the script without learning much more about Python (I have **zero** experience with Python - I'm a PHP/Ruby/JS developer).

I'm creating a fork and will push my minor modification that implements my suggested change to it. Here's the commit hash to the commit in which you can find my modification: [af93250e4e514410a65ca1bc2d53c1f2f13e7404](https://github.com/anandpathaksharma/quicktile/commit/af93250e4e514410a65ca1bc2d53c1f2f13e7404).

Once again, thanks for the excellent tool and your wonderful work!

**Comment by ssokolow** [comment]
There. Fixed in `master`. Sorry for taking three years to get to this.

I wish I had a good excuse but, really, QuickTile was something I kept putting off and putting off until I finally replaced my middle monitor with a 1920x1080 display and, suddenly, it wasn't "good enough" anymore.
