### ISSUE TITLE
Long lines in terminal lines are not wrapped

### ISSUE THREAD

**Issue by imran-uk** [ssokolow/quicktile#47]
I cannot reproduce this consistently but to try it:

* open a terminal eg. gnome-terminal or mate-terminal
* snap the window to the left or right half of the screen
* type "env" or other command which produces some long lines
* observe the long lines not being wrapped

I observed this when I ssh'd to a Centos6 server which is running zsh. My host machine is Debian Wheezy running MATE 1.6.0.

I am using quicktile 0.2.2

**Comment by ssokolow** [comment]
QuickTile just looks up the currently active window and asks your window manager to resize it to a specific preset. It doesn't even perform the resize itself.

The fact that your terminal reacts badly to being resized is not QuickTile's fault.
