### ISSUE TITLE
emacs grabs key commands

### ISSUE THREAD

**Issue by jobevers** [ssokolow/quicktile#48]
Just installed quicktile; when trying to resize an emacs window it instead prints out a message saying that the key combination is undefined.

**Comment by ssokolow** [comment]
I'm not sure how that would be possible. QuickTile uses the X11 XGrabKey function to take exclusive control of the key combos it listens for.

The only thing that should be able to override a successful XGrabKey is the XGrabKeyboard function intended for implementing secure password dialogs and, if that were in use, it would prevent **all** global hotkeys from functioning.

What do you get when launching quicktile in a terminal with `--debug`? Are there any messages about failing to bind keys?

**Comment by jobevers** [comment]
I'll take a look when I get the chance.  Thanks for the quick response!

**Comment by jobevers** [comment]
I'm not sure what I changed, but it seems to be working now. Thanks for writing the tool!
