### ISSUE TITLE
Fedora 22 quicktile rpm requirements fyi

### ISSUE THREAD

**Issue by fastrizwaan** [ssokolow/quicktile#56]
# Ubuntu:
sudo apt-get install python python-gtk2 python-xlib python-dbus python-wnck

# Fedora 22
sudo dnf install python pygtk2 pygobject2 dbus-python gnome-python2-libwnck

# Fedora 21
sudo yum install python pygtk2 pygobject2 dbus-python gnome-python2-libwnck

**Comment by ssokolow** [comment]
Thanks. I've added them to the README.
