### ISSUE TITLE
Quicktile not aligning properly

### ISSUE THREAD

**Issue by revoxx5** [ssokolow/quicktile#70]
I'm using Ubuntu x64 on a VM
When I align it to the left or right side, there are gaps and the window goes below screen height. As you can see from the screenshot, when I aligned my terminal to the left side, there is a gap between the terminal window and top + left areas. I have to manually drag the window to fix it's positioning
![2017-01-01-144101_1920x1080_scrot](https://cloud.githubusercontent.com/assets/15708420/21582678/6c8442d4-d030-11e6-86f7-c7141e590c1f.png)

**Comment by ssokolow** [comment]
Unfortunately, that's a known bug in Unity and, since the window manager has final say on where windows get placed, it's free to mangle QuickTile's requests to reposition windows.

**Comment by revoxx5** [comment]
@ssokolow  how would I go about doing that?

**Comment by ssokolow** [comment]
Doing what?

I'm saying that this is a bug in Unity, not QuickTile. (QuickTile asks for the right positions and Unity puts the windows in the wrong places.)

**Comment by revoxx5** [comment]
@ssokolow I meant when you said "it's free to mangle QuickTile's requests to reposition windows", how would I do that? But I think I figured out the bug, I fiddled around with the Unity Window placement options in CCSM until I got it working. Thank you!

**Comment by ssokolow** [comment]
Would you mind explaining what you did so I have something to share if someone else asks me?

**Comment by revoxx5** [comment]
Yeah so I just disabled the Grid plugin which essentially does the same thing but both applications are in conflict of interest. I use CCSM to disable it, I may run some more tests to see if it is fully fixed, but it seemed fine for me.

**Comment by ssokolow** [comment]
Ahh, so I should expand my FAQ entry to address more than "Grid plugin stealing my QuickTile shortcuts".

**Comment by ssokolow** [comment]
There. I've added notes to the README and the FAQ.
