### ISSUE TITLE
Fedora 25: Wayland support

### ISSUE THREAD

**Issue by fmikker** [ssokolow/quicktile#75]
Hi.
I have been using this tool for about a year, and I have really gotten used to it in my daily workflow. Great app!

However, today I upgraded to Fedora 25 which comes with Wayland per default, and some functionality from quicktile is still available, but one specific thing can't be tiled anymore: Terminals.
Moving all other windows around with quicktile works just fine, but if the window is a terminal, the default key combination <CTRL>+<ALT>+KP_1-9 just writes the numbers from the keypad to the terminal buffer and the window does not move.

I have also tried to re-bind some default keybindings to (Top-Left, Bottom-Left) to <CTRL>+<ALT>+Z/X, but it makes no difference.

If I change from Wayland to Gnome X11, quicktile works again.

**Comment by ssokolow** [comment]
Wayland support for QuickTile is impossible. That's why I've made no effort to upgrade from GTK+ 2.x.

By design, under Wayland, only the compositor (Mutter/Kwin/Weston/etc.) has permission to meddle with the placement of other applications' windows.
